# Generated by Django 4.2.20 on 2025-04-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='dog_id',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
