# Generated by Django 4.2.19 on 2025-05-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dog_dog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
    ]
