# Generated by Django 4.2.20 on 2025-06-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_clubmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmembership',
            name='permanently_banned',
            field=models.BooleanField(default=False),
        ),
    ]
