# Generated by Django 4.2.20 on 2025-06-17 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_clubforumroom_clubforumcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubforumcomment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clubforumroom'),
        ),
    ]
