# Generated by Django 4.2.20 on 2025-06-28 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_clubprofile_cpc_document_clubprofile_cpc_issued_date_and_more'),
        ('core', '0008_alter_clubforumcomment_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('vaccine_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('date_administered', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('veterinarian_name', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dog')),
                ('vet_clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.vetclinicprofile')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
