# Generated by Django 4.2.20 on 2025-07-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_vaccinationrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='date_administered',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='next_due_date',
            field=models.DateField(blank=True),
        ),
    ]
