# Generated by Django 4.2.20 on 2025-07-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_vaccinationrecord_date_administered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
