# Generated by Django 4.2.20 on 2025-07-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_vaccinationrecord_options_ccvoannouncement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccvoannouncement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ccvo_announcement_images/'),
        ),
    ]
