# Generated by Django 4.2.20 on 2025-08-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_clubannouncement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubannouncement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='club_announcement_images/'),
        ),
    ]
