# Generated by Django 4.2.20 on 2025-08-04 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_clubprofile_cpc_document_clubprofile_cpc_issued_date_and_more'),
        ('core', '0017_alter_clubmembership_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubforumroom',
            name='club',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='accounts.clubprofile'),
            preserve_default=False,
        ),
    ]
