# Generated by Django 4.2.20 on 2025-08-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_clubforumroom_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmembership',
            name='status',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('removed', 'Removed')], default='pending', max_length=10),
        ),
    ]
