# Generated by Django 4.2.20 on 2025-08-26 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_avail', models.DateField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dog')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
            ],
            options={
                'ordering': ['-date_avail'],
                'indexes': [models.Index(fields=['date_avail'], name='core_servic_date_av_65c926_idx'), models.Index(fields=['service', 'date_avail'], name='core_servic_service_9b7f6d_idx')],
            },
        ),
    ]
