# Generated by Django 4.2.20 on 2025-08-28 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_servicerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='date_avail',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
