# Generated by Django 4.2.20 on 2025-05-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetclinicprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
