# Generated by Django 4.2.19 on 2025-05-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_vetclinicprofile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='petownerprofile',
            name='owner_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='vetclinicprofile',
            name='regular_clients',
            field=models.ManyToManyField(blank=True, related_name='linked_vets', to='accounts.petownerprofile'),
        ),
    ]
