# Generated by Django 4.2.19 on 2025-05-03 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_petownerprofile_owner_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubprofile',
            old_name='social_email',
            new_name='admin_email',
        ),
        migrations.RemoveField(
            model_name='petownerprofile',
            name='social_email',
        ),
        migrations.RemoveField(
            model_name='vetclinicprofile',
            name='social_email',
        ),
    ]
