# Generated by Django 4.2.20 on 2025-05-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_social_email_clubprofile_admin_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vetclinicprofile',
            name='license_number',
        ),
        migrations.AddField(
            model_name='vetclinicprofile',
            name='business_permit_number',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vetclinicprofile',
            name='issuing_office',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
