# Generated by Django 4.2.20 on 2025-05-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_vetclinicprofile_license_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/defaultprofile.png', null=True, upload_to='profile_pics/'),
        ),
    ]
