# Generated by Django 4.2.20 on 2025-05-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprofile',
            name='cpc_document',
            field=models.FileField(blank=True, null=True, upload_to='cpc_docs/'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='cpc_issued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='has_professional_services',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='ptr_document',
            field=models.FileField(blank=True, null=True, upload_to='ptr_docs/'),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='ptr_issued_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
