# Generated by Django 4.2.20 on 2025-09-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_clubprofile_cpc_document_clubprofile_cpc_issued_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetclinicprofile',
            name='bp_document',
            field=models.FileField(blank=True, null=True, upload_to='bp_documents/'),
        ),
    ]
