# Generated by Django 4.2.20 on 2025-09-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_vetclinicprofile_bp_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetclinicprofile',
            name='is_operating',
            field=models.BooleanField(default=False),
        ),
    ]
