# Generated by Django 4.2.20 on 2025-09-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_vetclinicprofile_is_operating'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetclinicprofile',
            name='is_requesting_access',
            field=models.BooleanField(default=False),
        ),
    ]
